inherit_from: .rubocop_todo.yml

AllCops:
  UseCache: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

  Exclude:
    - "tmp/**/*"
    - "log/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ColonMethodCall:
  Exclude:
    - "lib/persistence/relations/**/*"

Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - "lib/persistence/relations/**/*"
