language: ruby

dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql

cache: bundler

rvm:
  - 2.4.1

before_install:
  - bundle config github.https true
  - npm install -g dredd@4.3.0

before_script:
  - cp .env.ci .env
  - psql -c 'create database elias_test;' -U postgres
  - psql elias_test -U postgres < db/structure.sql
  - bundle exec rubocop
  - dredd
