language: ruby

dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql

cache: bundler

rvm:
  - 2.4.1

before_script:
  - psql -c 'create database elias_test;' -U postgres

script:
  - bundle exec rubocop
